version: '3.3'

services:

    cache:
        image: redis:latest
        container_name: redis
        ports:
            - 6379:6379

    websocket:
        container_name: ws-api
        build: '.'
        links:
            - cache:cache
        command: /app/websocket
        environment:
            - PORT=8008
            - CACHE_HOST=cache
        ports:
            - 8008:8008

    consumer:
        build: '.'
        links:
            - cache:cache
        command: /app/consumer
        environment:
            - CACHE_HOST=cache

    redis-insights:
        container_name: redis-insights
        image: redislabs/redisinsight
        ports: 
            - "8082:8001"